export enum Role {
  STUDENT = 'STUDENT',
  HOD = 'HOD',
  WOMEN_SAFETY_OFFICER = 'WOMEN_SAFETY_OFFICER',
  PRINCIPAL = 'PRINCIPAL',
  FACULTY = 'FACULTY',
  SECURITY = 'SECURITY',
  AUTHORIZED_STAFF = 'AUTHORIZED_STAFF',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum SensitivityLevel {
  NORMAL = 'NORMAL',
  CONFIDENTIAL = 'CONFIDENTIAL',
  RESTRICTED = 'RESTRICTED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ComplaintStatus {
  SUBMITTED = 'SUBMITTED',
  RECEIVED = 'RECEIVED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  REOPENED = 'REOPENED',
  CLOSED = 'CLOSED',
  REJECTED = 'REJECTED',
}

export enum EscalationLevel {
  NONE = 'NONE',
  LEVEL_1 = 'LEVEL_1',
  LEVEL_2 = 'LEVEL_2',
  LEVEL_3 = 'LEVEL_3',
}

export enum RejectionReason {
  DUPLICATE = 'DUPLICATE',
  OUTSIDE_INSTITUTION_SCOPE = 'OUTSIDE_INSTITUTION_SCOPE',
  INSUFFICIENT_INFORMATION = 'INSUFFICIENT_INFORMATION',
  UNABLE_TO_VERIFY = 'UNABLE_TO_VERIFY',
  TEST_DEMO = 'TEST_DEMO',
  OTHER_AUTHORIZED = 'OTHER_AUTHORIZED',
}

export enum SosStatus {
  TRIGGERED = 'TRIGGERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  FALSE_ALARM = 'FALSE_ALARM',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  COMPLAINT_CREATED = 'COMPLAINT_CREATED',
  COMPLAINT_STATUS_UPDATED = 'COMPLAINT_STATUS_UPDATED',
  COMPLAINT_ASSIGNED = 'COMPLAINT_ASSIGNED',
  COMPLAINT_RESOLVED = 'COMPLAINT_RESOLVED',
  COMPLAINT_CLOSED = 'COMPLAINT_CLOSED',
  COMPLAINT_REJECTED = 'COMPLAINT_REJECTED',
  COMPLAINT_REOPENED = 'COMPLAINT_REOPENED',
  COMPLAINT_TRANSFERRED = 'COMPLAINT_TRANSFERRED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  SYSTEM = 'SYSTEM',
}
